### ISSUE TITLE
Font colours not displaying as shown

### ISSUE THREAD

**Issue by ka0s420** [IvanDmitriev1/Visual-Assist-Dark-Theme-for-VS#2]
The reason I like this theme is because of the orange text colours etc, but when using the theme, the colours are not the same as in the picture shown. This is what it looks like in my visual studio community 2022:

![Capture](https://github.com/IvanDmitriev1/Visual-Assist-Dark-Theme-for-VS/assets/23391250/598960c5-8542-4fa2-b172-4c40ad8d422d)

**Comment by IvanDmitriev1** [comment]
![image](https://github.com/IvanDmitriev1/Visual-Assist-Dark-Theme-for-VS/assets/42055372/7343c919-c212-4f57-83b7-f4611499ced5)

But also I want to add support a new UI in VS, but now I can't find and change those element.

**Comment by IvanDmitriev1** [comment]
And now theme broken again ...
![image](https://github.com/IvanDmitriev1/Visual-Assist-Dark-Theme-for-VS/assets/42055372/6ace4420-ef7a-4653-b7e3-bb5fa64ffdd0)

**Comment by IvanDmitriev1** [comment]
Can you check if it is working correctly?

**Comment by ka0s420** [comment]
> Can you check if it is working correctly?

I don't understand what you want me to do. There is no updated version of the theme to test, so I assume you want me to change a setting or something?

**Comment by IvanDmitriev1** [comment]
Download from [here](https://github.com/IvanDmitriev1/Visual-Assist-Dark-Theme-for-VS/actions/runs/7456536246)

**Comment by ka0s420** [comment]
Yeah, that new version fixes it! :) The only thing noticeable is that on the themes list the name is VisualAssistDark(45) <- not sure what the number at the end means, though it doesn't matter to me particularly, but none of the other installed themes have it. Thanks for fixing this up, you were surprising quick to respond and fix - very cool <3

**Comment by ka0s420** [comment]
Just for reference it looks like this now as it should :

![Capture](https://github.com/IvanDmitriev1/Visual-Assist-Dark-Theme-for-VS/assets/23391250/099e0135-1ce1-4b46-bd62-22b2d449096c)

**Comment by HyperHacker23** [comment]
> Just for reference it looks like this now as it should :
> 
> ![Capture](https://github.com/IvanDmitriev1/Visual-Assist-Dark-Theme-for-VS/assets/23391250/099e0135-1ce1-4b46-bd62-22b2d449096c)

its not looking like this now
